name: publish-ms-projects
on:
  push:
    branches: [ "main" ]
    paths:
      - "services/ms-projects/**"
      - "Dockerfile"
      - ".github/workflows/docker-publish-ms-projects.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USER }}/pjbl-projects:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USER }}/pjbl-projects:latest \
            --build-arg SERVICE_PATH=services/ms-projects \
            --build-arg START_CMD="node dist/index.js" \
            --build-arg HAS_BUILD=true \
            .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/pjbl-projects:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USER }}/pjbl-projects:latest
