name: Publish MS Orders
on:
  push:
    branches: ["main"]
    paths: ["services/ms-orders/**"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: services/ms-orders }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: services/ms-orders
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USER }}/pjbl-carbon-ms-orders:${{ github.sha }}

